### ISSUE TITLE
中文版的模型或者中文版的vocab.bpe文件

### ISSUE THREAD

**Issue by RyanYip-Kat** [THU-KEG/KEPLER#10]
如果我想训练一个中文版的模型，请问你们是否有中文版的开源模型或者中文版的gpt2_bpe/vocab.bpe 文件，可否分享下？谢谢！

**Comment by Bakser** [comment]
您好，我们没有训过中文版的模型，也没有处理过中文的BPE分词词表。您可以使用[fairseq的bpe](https://github.com/pytorch/fairseq/blob/1bba712622b8ae4efb3eb793a8a40da386fe11d0/fairseq/data/encoders/gpt2_bpe.py)在自己的中文语料上训词表，或者参考fairseq中某些支持中文的模型的词表，比如[XLM-RoBERTa](https://github.com/pytorch/fairseq/tree/2fd9d8a972794ba919174baf0d1828a5a4c626f3/examples/xlmr)。
