### ISSUE TITLE
模型转变为transformers结构

### ISSUE THREAD

**Issue by Macielyoung** [THU-KEG/KEPLER#11]
使用给出的示例转transformers模型结构时，出现KeyError: 'MLMetKE'的问题，想问一下怎么解决

**Comment by Bakser** [comment]
您可以关注下运行脚本时调用的fairseq库是否是我们这个repo中release的版本，原始的fairseq是没有MLMetKE这个我们的训练任务的。

**Comment by Macielyoung** [comment]
使用release版本的可以了。我一开始看了转换要求，就直接去安装了0.8.0版本的fairseq了😂😂

**Comment by Bakser** [comment]
好的
