### ISSUE TITLE
about the entity type

### ISSUE THREAD

**Issue by ShellingFord221** [THU-KEG/KEPLER#12]
Hi, could you please provide entity type file for all entities in the Wiki triplets, so as to I can do some statistics like Table 2? Thanks!

**Comment by Bakser** [comment]
Hi, the entity type information has already been contained in the knowledge graph. You can retrieve all the facts of the `P31` (`instance_of`) relation and will find that the head entities are the ordinary entities and the tail entities are the entity types.
