### ISSUE TITLE
Pre-training cost of KEPLER

### ISSUE THREAD

**Issue by finiteautomata** [THU-KEG/KEPLER#14]
First of all, congratulations on your amazing work. 

I have read your paper and I was wondering how much pre-training you spent on KEPLER. That is, how many steps was it trained for, how much time it took, and on what hardware. As far as I understand, you used a 12K batch size and `RoBERTa` weights as a starting point, but I couldn't find information about the computational resources needed to train your model.

Thanks!

**Comment by Bakser** [comment]
Hi, thanks for your interest in our work.

As shown in the paper, we use the models pre-trained with 10 and 30 epochs for NLP and KE, respectively.  Regarding the hardware and time, we use 64 Nvidia V100 (16GB) GPUs during pre-training and I remember it takes about 1 day to train 10 epochs.

Hope this information could help you.
