### ISSUE TITLE
Unable to download Wikidata5m

### ISSUE THREAD

**Issue by WenxiongLiao** [THU-KEG/KEPLER#17]
It seems that all files from this link (https://deepgraphlearning.github.io/project/wikidata5m) are not available for download anymore. Does the author have a new download link?
![image](https://user-images.githubusercontent.com/25845940/177517475-1685be63-3450-4af0-91ad-2d6c97bb8896.png)

**Comment by wwymak** [comment]
Not sure if you're still having issues but the download links work for me...
