### ISSUE TITLE
Generating knowledge embeddings with KEPLER 

### ISSUE THREAD

**Issue by dangnguyenngochai** [THU-KEG/KEPLER#19]
Hello,
How can i use KEPLER to generating knowledge embedding using the graph triplets without feeding the model any entity description ? From what I read from your paper, it was possible but I can not seem to find the instructions to do so in your repo ?

**Comment by Bakser** [comment]
Hi, KEPLER cannot work without entity descriptions. For your need, you may replace the entity descriptions with entity names or just entity IDs to see if it works, but I am afraid it won't work well since this scenario is so different from our design.
