### ISSUE TITLE
Tail entity and relation swapped?

### ISSUE THREAD

**Issue by Avmb** [THU-KEG/KEPLER#21]
It seems that the tail entity and the relation are swapped here. If I try to pretrain the model with data generated with this script I get an error because the relation indices are larger than the relation embedding matrix.

https://github.com/THU-KEG/KEPLER/blob/14f82c2d0e53e44f3d5eb1be43c7aa8d2722b523/examples/KEPLER/Pretrain/KGpreprocess.py#L23

**Comment by Bakser** [comment]
Thanks a lot for pointing this out! This coordinates with our previous data format and I forgot to change it.
