### ISSUE TITLE
WikiData5M国内下载不稳定

### ISSUE THREAD

**Issue by meteorlin** [THU-KEG/KEPLER#24]
您好，在国内下载WikiData5M时总是下没多少就断开了，请问作者能提供一个在国内比较稳定的下载源吗？
![image](https://user-images.githubusercontent.com/49402403/206859876-b12dd341-f39b-4ce5-a896-2279ed3e89ed.png)

**Comment by Eutopun** [comment]
您好，请问您下载到数据集了吗，能方便给个吗？找了很久  好像都失效了

**Comment by Bakser** [comment]
您好，我增加了了一份清华大学云盘的下载源（https://cloud.tsinghua.edu.cn/d/ebddf21e78c8494d9b0a/），希望能有帮助。
