### ISSUE TITLE
MLM/dict.txt

### ISSUE THREAD

**Issue by wangcaicai666** [THU-KEG/KEPLER#26]
你好，请问执行预训练命令一直提醒找不到MLM/dict.txt，仔细查找了并没有任何命令可以得到dict.txt，包括MLM里面数据预处理的命令

**Comment by Bakser** [comment]
您好，MLM数据预处理请参考RoBERTa原始文档`examples/roberta/README.pretraining.md`，其中有`wget -O gpt2_bpe/dict.txt https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/dict.txt`命令可以下载`dict.txt`
