### ISSUE TITLE
The construction of Wikidata5m on inductive settings

### ISSUE THREAD

**Issue by wxxw-blip** [THU-KEG/KEPLER#27]
请问 在inductive settings下train,valid,test集是怎么构建的，test里的所有实体都是unseen的吗

**Comment by DaliaDawod** [comment]
could you figure out --entity2id and --relation2id in the args? @wxxw-blip

**Comment by Bakser** [comment]
您好，请参考[我们的论文](https://bakser.github.io/files/TACL-KEPLER/KEPLER.pdf)中3.2节的描述。train\valid\test集合的实体是两两不相交的。具体来说，构建方式可以简单理解为采样两个不相交的子图作为valid\test集，并将所有与这两个子图相连的实体从train中删除。
