### ISSUE TITLE
--entity2id and --relation2id in ke_tools/evaluate_trans_transductive.py

### ISSUE THREAD

**Issue by DaliaDawod** [THU-KEG/KEPLER#28]
What are the json files for these args --entity2id and --relation2id?

**Comment by Bakser** [comment]
Hi, these two arguments are not two fixed files that I can just provide for you. You are supposed to generate it for your used dataset as the comment introduced. 
```
--entity2id: a json file that maps entity names (in the dataset) to the indices in the entity embedding numpy file, where the key is the entity names in the dataset, and the value is the indice in the numpy file.
--relation2id: a json file that maps relation names (in the dataset) to the indices in the relation embedding numpy file.
```
All you need to do is to map the entity/relation names (like Q29387131/P31) to their indices (like 0,1) in the output embedding files generated by `examples/KEPLER/KE/generate_embeddings.py`.
