### ISSUE TITLE
NCCL是必须要有的吗

### ISSUE THREAD

**Issue by GoddessLuBoYan** [THU-KEG/KEPLER#5]
只使用CUDA不行嘛
（目前还在下载各种数据集和公开的模型，暂时还没有运行代码）

**Comment by Bakser** [comment]
Hi, NCCL是用于多卡通信的，如果不使用多卡并行就可以不用NCCL。但以预训练的规模只用单卡会非常慢，因此还是建议尽量使用多卡。
