### ISSUE TITLE
Could you release the example code for evaluating tacred test results on pre-trained model

### ISSUE THREAD

**Issue by Coopercoppers** [THU-KEG/KEPLER#6]

**Comment by Bakser** [comment]
Hi, the TACRED example script is at https://github.com/THU-KEG/KEPLER/blob/main/examples/KEPLER/TACRED/TACRED.sh .
@gaotianyu1350 please leave a message here when you finish the OpenNRE example.

**Comment by Coopercoppers** [comment]
ok, great, thank you very much
